name: Deploy to SAP Cloud Foundry

on:
  push:
    branches:
      - main  # Adjust as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18 # Use latest LTS version

      - name: Install Dependencies
        run: |
          npm config set @sap:registry https://npm.sap.com
          npm install
          npm install --save express body-parser axios

      - name: Install Cloud Foundry CLI
        run: |
          wget "https://packages.cloudfoundry.org/stable?release=linux64-binary&version=8.9.0&source=github-rel" -O cf-cli.tgz
          tar -xvzf cf-cli.tgz
          sudo mv cf8 /usr/local/bin/cf
          sudo chmod +x /usr/local/bin/cf
          cf --version  

      - name: Authenticate to Cloud Foundry
        env:
          CF_API: https://api.cf.us10-001.hana.ondemand.com
          CF_ACCESS_TOKEN: ${{ secrets.CF_ACCESS_TOKEN }}
        run: |
          cf api $CF_API
          echo "Using OAuth Token for authentication..."
          export CF_OAUTH_TOKEN="$CF_OAUTH_TOKEN"
          cf target
        
          
      - name: Deploy Application
        run: cf push ${{ github.event.repository.name }}
